# Generated by Django 6.0 on 2025-12-31 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('#5d8aa8', 'Air blue'), ('#9966cc', 'Amethust'), ('#008000', 'Apple Green'), ('#ff033e', 'Red rose'), ('#ffe135', 'Banana yellow'), ('#ff6500', 'Sunset'), ('#000000', 'Black')], default='Black', max_length=30)),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_rel', to='task_app.folder'),
        ),
    ]
