# Generated by Django 6.0 on 2026-02-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='folder',
            name='color',
            field=models.CharField(choices=[('#77acc7', '🔵Air blue'), ('#9966cc', '🟣Amethust'), ('#008000', '🟢Apple Green'), ('#ff033e', '🔴Red rose'), ('#ffe135', '🟡Banana yellow'), ('#ff6500', '🟠Sunset'), ('#000000', '⚫Black')], default='Black', max_length=30),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
